# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: captcha.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'captcha.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcaptcha.proto\x12\x07\x63\x61ptcha\"\x14\n\x12HealthCheckRequest\"2\n\x13HealthCheckResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t\"O\n\rSolveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x0f\n\x07\x65lapsed\x18\x04 \x01(\x03\"8\n\x12RecaptchaV2Request\x12\x10\n\x08site_key\x18\x01 \x01(\t\x12\x10\n\x08page_url\x18\x02 \x01(\t2\xa2\x01\n\rCaptchaSolver\x12G\n\x10SolveRecaptchaV2\x12\x1b.captcha.RecaptchaV2Request\x1a\x16.captcha.SolveResponse\x12H\n\x0bHealthCheck\x12\x1b.captcha.HealthCheckRequest\x1a\x1c.captcha.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'captcha_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=26
  _globals['_HEALTHCHECKREQUEST']._serialized_end=46
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=48
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=98
  _globals['_SOLVERESPONSE']._serialized_start=100
  _globals['_SOLVERESPONSE']._serialized_end=179
  _globals['_RECAPTCHAV2REQUEST']._serialized_start=181
  _globals['_RECAPTCHAV2REQUEST']._serialized_end=237
  _globals['_CAPTCHASOLVER']._serialized_start=240
  _globals['_CAPTCHASOLVER']._serialized_end=402
# @@protoc_insertion_point(module_scope)
